Clever/Controllers/CompaniesKKController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Clever.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Clever.Controllers
{
    public class CompaniesKKController : Controller
    {
        private readonly HttpApiClientController _HttpApiClient;

        public CompaniesKKController(HttpApiClientController HttpApiClient)
        {
            _HttpApiClient = HttpApiClient;
        }

        public async Task<IActionResult> Index(string SortOrder,
            string Search,
            string BINFilter,
            string NameKKFilter,
            string NameRUFilter,
            DateTime? DateRegisterFilter,
            string OKEDFilter,
            string ActivityKindKKFilter,
            string ActivityKindRUFilter,
            string OKEDSecondaryFilter,
            string KRPFilter,
            string KRPNameKKFilter,
            string KRPNameRUFilter,
            string CATOFilter,
            string LocalityKKFilter,
            string LocalityRUFilter,
            string LegalAddressFilter,
            string HeadNameFilter,
            int? PageSize,
            int? Page)
        {
            List<CompanyKK> companiesKK = new List<CompanyKK>();

            ViewBag.BINFilter = BINFilter;
            ViewBag.NameKKFilter = NameKKFilter;
            ViewBag.NameRUFilter = NameRUFilter;
            ViewBag.DateRegisterFilter = DateRegisterFilter;
            ViewBag.OKEDFilter = OKEDFilter;
            ViewBag.ActivityKindKKFilter = ActivityKindKKFilter;
            ViewBag.ActivityKindRUFilter = ActivityKindRUFilter;
            ViewBag.OKEDSecondaryFilter = OKEDSecondaryFilter;
            ViewBag.KRPFilter = KRPFilter;
            ViewBag.KRPNameKKFilter = KRPNameKKFilter;
            ViewBag.KRPNameRUFilter = KRPNameRUFilter;
            ViewBag.CATOFilter = CATOFilter;
            ViewBag.LocalityKKFilter = LocalityKKFilter;
            ViewBag.LocalityRUFilter = LocalityRUFilter;
            ViewBag.LegalAddressFilter = LegalAddressFilter;
            ViewBag.HeadNameFilter = HeadNameFilter;

            ViewBag.BINSort = SortOrder == "BIN" ? "BINDesc" : "BIN";
            ViewBag.NameKKSort = SortOrder == "NameKK" ? "NameKKDesc" : "NameKK";
            ViewBag.NameRUSort = SortOrder == "NameRU" ? "NameRUDesc" : "NameRU";
            ViewBag.DateRegisterSort = SortOrder == "DateRegister" ? "DateRegisterDesc" : "DateRegister";
            ViewBag.OKEDSort = SortOrder == "OKED" ? "OKEDDesc" : "OKED";
            ViewBag.ActivityKindKKSort = SortOrder == "ActivityKindKK" ? "ActivityKindKKDesc" : "ActivityKindKK";
            ViewBag.ActivityKindRUSort = SortOrder == "ActivityKindRU" ? "ActivityKindRUDesc" : "ActivityKindRU";
            ViewBag.OKEDSecondarySort = SortOrder == "OKEDSecondary" ? "OKEDSecondaryDesc" : "OKEDSecondary";
            ViewBag.KRPSort = SortOrder == "KRP" ? "KRPDesc" : "KRP";
            ViewBag.KRPNameKKSort = SortOrder == "KRPNameKK" ? "KRPNameKKDesc" : "KRPNameKK";
            ViewBag.KRPNameRUSort = SortOrder == "KRPNameRU" ? "KRPNameRUDesc" : "KRPNameRU";
            ViewBag.CATOSort = SortOrder == "CATO" ? "CATODesc" : "CATO";
            ViewBag.LocalityKKSort = SortOrder == "LocalityKK" ? "LocalityKKDesc" : "LocalityKK";
            ViewBag.LocalityRUSort = SortOrder == "LocalityRU" ? "LocalityRUDesc" : "LocalityRU";
            ViewBag.LegalAddressSort = SortOrder == "LegalAddress" ? "LegalAddressDesc" : "LegalAddress";
            ViewBag.HeadNameSort = SortOrder == "HeadName" ? "HeadNameDesc" : "HeadName";

            string url = "api/CompaniesKK",
                route = "",
                routeCount = "";
            if (!string.IsNullOrEmpty(SortOrder))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"SortOrder={SortOrder}";
            }
            if (!string.IsNullOrEmpty(Search))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Search={Search}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"Search={Search}";
            }
            if (!string.IsNullOrEmpty(BINFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"BIN={BINFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"BIN={BINFilter}";
            }
            if (!string.IsNullOrEmpty(NameKKFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"NameKK={NameKKFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"NameKK={NameKKFilter}";
            }
            if (!string.IsNullOrEmpty(NameRUFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"NameRU={NameRUFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"NameRU={NameRUFilter}";
            }
            if (DateRegisterFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"DateRegister={DateRegisterFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"DateRegister={DateRegisterFilter.ToString()}";
            }
            if (!string.IsNullOrEmpty(OKEDFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"OKED={OKEDFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"OKED={OKEDFilter}";
            }
            if (!string.IsNullOrEmpty(ActivityKindKKFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"ActivityKindKK={ActivityKindKKFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"ActivityKindKK={ActivityKindKKFilter}";
            }
            if (!string.IsNullOrEmpty(ActivityKindRUFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"ActivityKindRU={ActivityKindRUFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"ActivityKindRU={ActivityKindRUFilter}";
            }
            if (!string.IsNullOrEmpty(OKEDSecondaryFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"OKEDSecondary={OKEDSecondaryFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"OKEDSecondary={OKEDSecondaryFilter}";
            }
            if (!string.IsNullOrEmpty(KRPFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"KRP={KRPFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"KRP={KRPFilter}";
            }
            if (!string.IsNullOrEmpty(KRPNameKKFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"KRPNameKK={KRPNameKKFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"KRPNameKK={KRPNameKKFilter}";
            }
            if (!string.IsNullOrEmpty(KRPNameRUFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"KRPNameRU={KRPNameRUFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"KRPNameRU={KRPNameRUFilter}";
            }
            if (!string.IsNullOrEmpty(CATOFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"CATO={CATOFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"CATO={CATOFilter}";
            }
            if (!string.IsNullOrEmpty(LocalityKKFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"LocalityKK={LocalityKKFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"LocalityKK={LocalityKKFilter}";
            }
            if (!string.IsNullOrEmpty(LocalityRUFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"LocalityRU={LocalityRUFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"LocalityRU={LocalityRUFilter}";
            }
            if (!string.IsNullOrEmpty(LegalAddressFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"LegalAddress={LegalAddressFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"LegalAddress={LegalAddressFilter}";
            }
            if (!string.IsNullOrEmpty(HeadNameFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"HeadName={HeadNameFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"HeadName={HeadNameFilter}";
            }
            IConfigurationSection pageSizeListSection = Startup.Configuration.GetSection("PageSizeList");

Clever/Views/CompaniesKK/Create.cshtml
@model Clever.Models.CompanyKK
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer["Create"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["Create"]</h2>

<h4>@SharedLocalizer["CompanyKK"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BIN" class="control-label"></label>
                <input asp-for="BIN" class="form-control" />
                <span asp-validation-for="BIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameKK" class="control-label"></label>
                <input asp-for="NameKK" class="form-control" />
                <span asp-validation-for="NameKK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameRU" class="control-label"></label>
                <input asp-for="NameRU" class="form-control" />
                <span asp-validation-for="NameRU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateRegister" class="control-label"></label>
                <input asp-for="DateRegister" class="form-control" />
                <span asp-validation-for="DateRegister" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OKED" class="control-label"></label>
                <input asp-for="OKED" class="form-control" />
                <span asp-validation-for="OKED" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActivityKindKK" class="control-label"></label>
                <input asp-for="ActivityKindKK" class="form-control" />
                <span asp-validation-for="ActivityKindKK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActivityKindRU" class="control-label"></label>
                <input asp-for="ActivityKindRU" class="form-control" />
                <span asp-validation-for="ActivityKindRU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OKEDSecondary" class="control-label"></label>
                <input asp-for="OKEDSecondary" class="form-control" />
                <span asp-validation-for="OKEDSecondary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KRP" class="control-label"></label>
                <input asp-for="KRP" class="form-control" />
                <span asp-validation-for="KRP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KRPNameKK" class="control-label"></label>
                <input asp-for="KRPNameKK" class="form-control" />
                <span asp-validation-for="KRPNameKK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KRPNameRU" class="control-label"></label>
                <input asp-for="KRPNameRU" class="form-control" />
                <span asp-validation-for="KRPNameRU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CATO" class="control-label"></label>
                <input asp-for="CATO" class="form-control" />
                <span asp-validation-for="CATO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityKK" class="control-label"></label>
                <input asp-for="LocalityKK" class="form-control" />
                <span asp-validation-for="LocalityKK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityRU" class="control-label"></label>
                <input asp-for="LocalityRU" class="form-control" />
                <span asp-validation-for="LocalityRU" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegalAddress" class="control-label"></label>
                <input asp-for="LegalAddress" class="form-control" />
                <span asp-validation-for="LegalAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HeadName" class="control-label"></label>
                <input asp-for="HeadName" class="form-control" />
                <span asp-validation-for="HeadName" class="text-danger"></span>
            </div>
            <div hidden="hidden">
                @Html.Editor("Search", null, new { value = ViewBag.Search })
                @Html.Editor("SortOrder", null, new { value = ViewBag.SortOrder })
                @Html.Editor("BIN", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NameKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NameRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("DateRegister", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("OKED", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ActivityKindKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ActivityKindRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("OKEDSecondary", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRP", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRPNameKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRPNameRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("CATO", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LocalityKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LocalityRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LegalAddress", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("HeadName", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("PageSize", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("Page", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </div>
            <div class="form-group">
                <input type="submit" value="@SharedLocalizer["Create"]" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Search = ViewBag.Search, Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, BINFilter = ViewBag.BINFilter, NameKKFilter = ViewBag.NameKKFilter, NameRUFilter = ViewBag.NameRUFilter, DateRegisterFilter = ViewBag.DateRegisterFilter, OKEDFilter = ViewBag.OKEDFilter, ActivityKindKKFilter = ViewBag.ActivityKindKKFilter, ActivityKindRUFilter = ViewBag.ActivityKindRUFilter, OKEDSecondaryFilter = ViewBag.OKEDSecondaryFilter, KRPFilter = ViewBag.KRPFilter, KRPNameKKFilter = ViewBag.KRPNameKKFilter, KRPNameRUFilter = ViewBag.KRPNameRUFilter, CATOFilter = ViewBag.CATOFilter, LocalityKKFilter = ViewBag.LocalityKKFilter, LocalityRUFilter = ViewBag.LocalityRUFilter, LegalAddressFilter = ViewBag.LegalAddressFilter, HeadNameFilter = ViewBag.HeadNameFilter })
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

<script>
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
    }
    $.validator.methods.number = function (value, element) {
        return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
    }
    //$.validator.methods.date = function (value, element) {
    //    return this.optional(element) || moment(value, "DD.MM.YYYY", true).isValid();
    //}
</script>

Clever/Views/CompaniesKK/UploadFiles.cshtml
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer["ImportFromFiles"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["UploadFiles"]</h2>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-form/jquery.form.js"></script>

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("UploadFiles", "CompaniesKK", FormMethod.Post, new { enctype = "multipart/form-data", id = "uploadform" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="col-md-2 control-label">Files</label>
                <input type="file" name="Files" multiple />
            </div>
            <div hidden="hidden">
                @Html.Editor("Search", null, new { value = ViewBag.Search })
                @Html.Editor("SortOrder", null, new { value = ViewBag.SortOrder })
                @Html.Editor("BIN", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NameKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NameRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("DateRegister", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("OKED", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ActivityKindKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ActivityKindRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("OKEDSecondary", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRP", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRPNameKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("KRPNameRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("CATO", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LocalityKK", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LocalityRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("LegalAddress", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("HeadName", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("PageSize", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("Page", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </div>
            <div class="form-group">
                <input type="submit" value="@SharedLocalizer["Upload"]" class="btn btn-default" />
            </div>
        }
    </div>
</div>

<div class="progress" style="width:50%">
    <div class="progress-bar"></div>
    <div class="percent">0%</div>
</div>

<div id="status"></div>

@if (!string.IsNullOrEmpty(ViewBag.Report))
{
    <div>
        @ViewBag.Report
    </div>
}

    <div>
        @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Search = ViewBag.Search, Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, BINFilter = ViewBag.BINFilter, NameKKFilter = ViewBag.NameKKFilter, NameRUFilter = ViewBag.NameRUFilter, DateRegisterFilter = ViewBag.DateRegisterFilter, OKEDFilter = ViewBag.OKEDFilter, ActivityKindKKFilter = ViewBag.ActivityKindKKFilter, ActivityKindRUFilter = ViewBag.ActivityKindRUFilter, OKEDSecondaryFilter = ViewBag.OKEDSecondaryFilter, KRPFilter = ViewBag.KRPFilter, KRPNameKKFilter = ViewBag.KRPNameKKFilter, KRPNameRUFilter = ViewBag.KRPNameRUFilter, CATOFilter = ViewBag.CATOFilter, LocalityKKFilter = ViewBag.LocalityKKFilter, LocalityRUFilter = ViewBag.LocalityRUFilter, LegalAddressFilter = ViewBag.LegalAddressFilter, HeadNameFilter = ViewBag.HeadNameFilter })
    </div>

<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        var bar = $('.progress-bar');
        var percent = $('.percent');
        var status = $('#status');
        $('#uploadform').ajaxForm({
            beforeSend: function () {
                status.empty();
                var percentVal = '0%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            complete: function (xhr) {
                status.html(xhr.responseText);
            }
        });
    });
</script>