Clever/Controllers/AirContaminantsRUController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Clever.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Clever.Controllers
{
    public class AirContaminantsRUController : Controller
    {
        private readonly HttpApiClientController _HttpApiClient;

        public AirContaminantsRUController(HttpApiClientController HttpApiClient)
        {
            _HttpApiClient = HttpApiClient;
        }

        public async Task<IActionResult> Index(string SortOrder,
            string NameFilter,
            string NumberCASFilter,
            string FormulaFilter,
            decimal? MaximumPermissibleConcentrationOneTimeMaximumFilter,
            decimal? MaximumPermissibleConcentrationDailyAverageFilter,
            int? HazardClassFilter,
            int? CodeFilter,
            decimal? ApproximateSafeExposureLevelFilter,
            int? PageSize,
            int? Page)
        {
            List<AirContaminantRU> airContaminantsRU = new List<AirContaminantRU>();

            ViewBag.NameFilter = NameFilter;
            ViewBag.NumberCASFilter = NumberCASFilter;
            ViewBag.FormulaFilter = FormulaFilter;
            ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter = MaximumPermissibleConcentrationOneTimeMaximumFilter;
            ViewBag.MaximumPermissibleConcentrationDailyAverageFilter = MaximumPermissibleConcentrationDailyAverageFilter;
            ViewBag.HazardClassFilter = HazardClassFilter;
            ViewBag.CodeFilter = CodeFilter;
            ViewBag.ApproximateSafeExposureLevelFilter = ApproximateSafeExposureLevelFilter;

            ViewBag.NameSort = SortOrder == "Name" ? "NameDesc" : "Name";
            ViewBag.NumberCASSort = SortOrder == "NumberCAS" ? "NumberCASDesc" : "NumberCAS";
            ViewBag.FormulaSort = SortOrder == "Formula" ? "FormulaDesc" : "Formula";
            ViewBag.MaximumPermissibleConcentrationOneTimeMaximumSort = SortOrder == "MaximumPermissibleConcentrationOneTimeMaximum" ? "MaximumPermissibleConcentrationOneTimeMaximumDesc" : "MaximumPermissibleConcentrationOneTimeMaximum";
            ViewBag.MaximumPermissibleConcentrationDailyAverageSort = SortOrder == "MaximumPermissibleConcentrationDailyAverage" ? "MaximumPermissibleConcentrationDailyAverageDesc" : "MaximumPermissibleConcentrationDailyAverage";
            ViewBag.HazardClassSort = SortOrder == "HazardClass" ? "HazardClassDesc" : "HazardClass";
            ViewBag.CodeSort = SortOrder == "Code" ? "CodeDesc" : "Code";
            ViewBag.ApproximateSafeExposureLevelSort = SortOrder == "ApproximateSafeExposureLevel" ? "ApproximateSafeExposureLevelDesc" : "ApproximateSafeExposureLevel";

            string url = "api/AirContaminantsRU",
                route = "",
                routeCount = "";
            if (!string.IsNullOrEmpty(SortOrder))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"SortOrder={SortOrder}";
            }
            if (!string.IsNullOrEmpty(NameFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Name={NameFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"Name={NameFilter}";
            }
            if (!string.IsNullOrEmpty(NumberCASFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"NumberCAS={NumberCASFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"NumberCAS={NumberCASFilter}";
            }
            if (!string.IsNullOrEmpty(FormulaFilter))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Formula={FormulaFilter}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"Formula={FormulaFilter}";
            }
            if (MaximumPermissibleConcentrationOneTimeMaximumFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"MaximumPermissibleConcentrationOneTimeMaximum={MaximumPermissibleConcentrationOneTimeMaximumFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"MaximumPermissibleConcentrationOneTimeMaximum={MaximumPermissibleConcentrationOneTimeMaximumFilter.ToString()}";
            }
            if (MaximumPermissibleConcentrationDailyAverageFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"MaximumPermissibleConcentrationDailyAverage={MaximumPermissibleConcentrationDailyAverageFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"MaximumPermissibleConcentrationDailyAverage={MaximumPermissibleConcentrationDailyAverageFilter.ToString()}";
            }
            if (HazardClassFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"HazardClass={HazardClassFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"HazardClass={HazardClassFilter.ToString()}";
            }
            if (CodeFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Code={CodeFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"Code={CodeFilter.ToString()}";
            }
            if (ApproximateSafeExposureLevelFilter != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"ApproximateSafeExposureLevel={ApproximateSafeExposureLevelFilter.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"ApproximateSafeExposureLevel={ApproximateSafeExposureLevelFilter.ToString()}";
            }
            IConfigurationSection pageSizeListSection = Startup.Configuration.GetSection("PageSizeList");
            var pageSizeList = pageSizeListSection.AsEnumerable();
            ViewBag.PageSizeList = new SelectList(pageSizeList.OrderBy(p => p.Key), "Value", "Value");
            if (PageSize == null)
            {
                PageSize = Convert.ToInt32(pageSizeList.Min(p => p.Value));
            }
            if (PageSize != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"PageSize={PageSize.ToString()}";
                if (Page == null)
                {
                    Page = 1;
                }
            }
            if (Page != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Page={Page.ToString()}";
            }
            HttpResponseMessage response = await _HttpApiClient.GetAsync(url + route),
                responseCount = await _HttpApiClient.GetAsync(url + "/count" + routeCount);
            if (response.IsSuccessStatusCode)
            {
                airContaminantsRU = await response.Content.ReadAsAsync<List<AirContaminantRU>>();
            }
            int airContaminantsRUCount = 0;
            if (responseCount.IsSuccessStatusCode)
            {
                airContaminantsRUCount = await responseCount.Content.ReadAsAsync<int>();
            }
            ViewBag.SortOrder = SortOrder;
            ViewBag.PageSize = PageSize;
            ViewBag.Page = Page != null ? (int)Page : 1;
            ViewBag.TotalPages = PageSize != null ? (int)(Math.Ceiling((decimal)airContaminantsRUCount / (decimal)PageSize)) : 1;
            ViewBag.StartPage = Page - 5;
            ViewBag.EndPage = Page + 4;
            if (ViewBag.StartPage <= 0)
            {
                ViewBag.EndPage -= (ViewBag.StartPage - 1);
                ViewBag.StartPage = 1;
            }
            if (ViewBag.EndPage > ViewBag.TotalPages)
            {
                ViewBag.EndPage = ViewBag.TotalPages;
                if (ViewBag.EndPage > 10)
                {
                    ViewBag.StartPage = ViewBag.EndPage - 9;
                }
            }
            
            return View(airContaminantsRU);
        }

        public async Task<IActionResult> Details(int? id,
            string SortOrder,
            string NameFilter,
            string NumberCASFilter,
            string FormulaFilter,
            decimal? MaximumPermissibleConcentrationOneTimeMaximumFilter,
            decimal? MaximumPermissibleConcentrationDailyAverageFilter,
            int? HazardClassFilter,
            int? CodeFilter,
            decimal? ApproximateSafeExposureLevelFilter,
            int? PageSize,
            int? Page)
        {
            AirContaminantRU airContaminantRU = null;
            HttpResponseMessage response = await _HttpApiClient.GetAsync($"api/AirContaminantsRU/{id.ToString()}");
            if (response.IsSuccessStatusCode)
            {
                airContaminantRU = await response.Content.ReadAsAsync<AirContaminantRU>();
            }
            ViewBag.SortOrder = SortOrder;
            ViewBag.PageSize = PageSize;
            ViewBag.Page = Page;
            ViewBag.NameFilter = NameFilter;
            ViewBag.NumberCASFilter = NumberCASFilter;
            ViewBag.FormulaFilter = FormulaFilter;
            ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter = MaximumPermissibleConcentrationOneTimeMaximumFilter;

Clever/Views/AirContaminantsRU/Create.cshtml
@model Clever.Models.AirContaminantRU
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer["Create"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["Create"]</h2>

<h4>@SharedLocalizer["AirContaminantRU"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberCAS" class="control-label"></label>
                <input asp-for="NumberCAS" class="form-control" />
                <span asp-validation-for="NumberCAS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Formula" class="control-label"></label>
                <input asp-for="Formula" class="form-control" />
                <span asp-validation-for="Formula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationOneTimeMaximum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationDailyAverage" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationDailyAverage" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationDailyAverage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HazardClass" class="control-label"></label>
                <input asp-for="HazardClass" class="form-control" />
                <span asp-validation-for="HazardClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApproximateSafeExposureLevel" class="control-label"></label>
                <input asp-for="ApproximateSafeExposureLevel" class="form-control" />
                <span asp-validation-for="ApproximateSafeExposureLevel" class="text-danger"></span>
            </div>
            <div hidden="hidden">
                @Html.Editor("SortOrder", null, new { value = ViewBag.SortOrder })
                @Html.Editor("NameFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NumberCASFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("FormulaFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("MaximumPermissibleConcentrationOneTimeMaximumFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("MaximumPermissibleConcentrationDailyAverageFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("HazardClassFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("CodeFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ApproximateSafeExposureLevelFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("PageSize", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("Page", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </div>
            <div class="form-group">
                <input type="submit" value="@SharedLocalizer["Create"]" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    @*<a asp-action="Index">Back to List</a>*@
    @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, NameFilter = ViewBag.NameFilter, NumberCASFilter = ViewBag.NumberCASFilter, FormulaFilter = ViewBag.FormulaFilter, MaximumPermissibleConcentrationOneTimeMaximumFilter = ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter, MaximumPermissibleConcentrationDailyAverageFilter = ViewBag.MaximumPermissibleConcentrationDailyAverageFilter, HazardClassFilter = ViewBag.HazardClassFilter, CodeFilter = ViewBag.CodeFilter, ApproximateSafeExposureLevelFilter = ViewBag.ApproximateSafeExposureLevelFilter })
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

<script>
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
    }
    $.validator.methods.number = function (value, element) {
        return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
    }
</script>

Clever/Views/AirContaminantsRU/Delete.cshtml
@model Clever.Models.AirContaminantRU
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = @SharedLocalizer["Delete"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["Delete"]</h2>

<h3>@SharedLocalizer["Delete"]?</h3>
<div>
    <h4>@SharedLocalizer["AirContaminantRU"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberCAS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberCAS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Formula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Formula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HazardClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HazardClass)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApproximateSafeExposureLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApproximateSafeExposureLevel)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div hidden="hidden">
            @Html.Editor("SortOrder", null, new { value = ViewBag.SortOrder })
            @Html.Editor("NameFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("NumberCASFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("FormulaFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("MaximumPermissibleConcentrationOneTimeMaximumFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("MaximumPermissibleConcentrationDailyAverageFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("HazardClassFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("CodeFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("ApproximateSafeExposureLevelFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("PageSize", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            @Html.Editor("Page", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
        </div>
        <input type="submit" value="@SharedLocalizer["Delete"]" class="btn btn-default" /> |
        @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, NameFilter = ViewBag.NameFilter, NumberCASFilter = ViewBag.NumberCASFilter, FormulaFilter = ViewBag.FormulaFilter, MaximumPermissibleConcentrationOneTimeMaximumFilter = ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter, MaximumPermissibleConcentrationDailyAverageFilter = ViewBag.MaximumPermissibleConcentrationDailyAverageFilter, HazardClassFilter = ViewBag.HazardClassFilter, CodeFilter = ViewBag.CodeFilter, ApproximateSafeExposureLevelFilter = ViewBag.ApproximateSafeExposureLevelFilter })
    </form>
</div>

Clever/Views/AirContaminantsRU/Details.cshtml
@model Clever.Models.AirContaminantRU
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = @SharedLocalizer["Details"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["Details"]</h2>

<div>
    <h4>@SharedLocalizer["AirContaminantRU"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberCAS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberCAS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Formula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Formula)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HazardClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HazardClass)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApproximateSafeExposureLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApproximateSafeExposureLevel)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |*@
    @Html.ActionLink(SharedLocalizer["Edit"], "Edit", new { Id = Model.Id, Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, NameFilter = ViewBag.NameFilter, NumberCASFilter = ViewBag.NumberCASFilter, FormulaFilter = ViewBag.FormulaFilter, MaximumPermissibleConcentrationOneTimeMaximumFilter = ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter, MaximumPermissibleConcentrationDailyAverageFilter = ViewBag.MaximumPermissibleConcentrationDailyAverageFilter, HazardClassFilter = ViewBag.HazardClassFilter, CodeFilter = ViewBag.CodeFilter, ApproximateSafeExposureLevelFilter = ViewBag.ApproximateSafeExposureLevelFilter }) |
    @*<a asp-action="Index">Back to List</a>*@
    @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, NameFilter = ViewBag.NameFilter, NumberCASFilter = ViewBag.NumberCASFilter, FormulaFilter = ViewBag.FormulaFilter, MaximumPermissibleConcentrationOneTimeMaximumFilter = ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter, MaximumPermissibleConcentrationDailyAverageFilter = ViewBag.MaximumPermissibleConcentrationDailyAverageFilter, HazardClassFilter = ViewBag.HazardClassFilter, CodeFilter = ViewBag.CodeFilter, ApproximateSafeExposureLevelFilter = ViewBag.ApproximateSafeExposureLevelFilter })
</div>

Clever/Views/AirContaminantsRU/UploadFiles.cshtml
@using Clever.Controllers
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<SharedResources> SharedLocalizer
@{
    ViewData["Title"] = SharedLocalizer["ImportFromFiles"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@SharedLocalizer["UploadFiles"]</h2>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-form/jquery.form.js"></script>

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("UploadFiles", "AirContaminantsRU", FormMethod.Post, new { enctype = "multipart/form-data", id = "uploadform" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="col-md-2 control-label">Files</label>
                <input type="file" name="Files" multiple />
            </div>
            <div hidden="hidden">
                @Html.Editor("SortOrder", null, new { value = ViewBag.SortOrder })
                @Html.Editor("NameFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("NumberCASFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("FormulaFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("MaximumPermissibleConcentrationOneTimeMaximumFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("MaximumPermissibleConcentrationDailyAverageFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("HazardClassFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("CodeFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("ApproximateSafeExposureLevelFilter", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("PageSize", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                @Html.Editor("Page", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </div>
            <div class="form-group">
                <input type="submit" value="@SharedLocalizer["Upload"]" class="btn btn-default" />
            </div>
        }
    </div>
</div>

<div class="progress" style="width:50%">
    <div class="progress-bar"></div>
    <div class="percent">0%</div>
</div>

<div id="status"></div>

@if (!string.IsNullOrEmpty(ViewBag.Report))
{
    <div>
        @ViewBag.Report
    </div>
}

<div>
    @Html.ActionLink(SharedLocalizer["BackToList"], "Index", new { Page = ViewBag.Page, PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, NameFilter = ViewBag.NameFilter, NumberCASFilter = ViewBag.NumberCASFilter, FormulaFilter = ViewBag.FormulaFilter, MaximumPermissibleConcentrationOneTimeMaximumFilter = ViewBag.MaximumPermissibleConcentrationOneTimeMaximumFilter, MaximumPermissibleConcentrationDailyAverageFilter = ViewBag.MaximumPermissibleConcentrationDailyAverageFilter, HazardClassFilter = ViewBag.HazardClassFilter, CodeFilter = ViewBag.CodeFilter, ApproximateSafeExposureLevelFilter = ViewBag.ApproximateSafeExposureLevelFilter })
</div>

<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        var bar = $('.progress-bar');
        var percent = $('.percent');
        var status = $('#status');
        $('#uploadform').ajaxForm({
            beforeSend: function () {
                status.empty();
                var percentVal = '0%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            complete: function (xhr) {
                status.html(xhr.responseText);
            }
        });
    });
</script>