Clever/Models/AirContaminant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clever.Models
{
    public class AirContaminant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NumberCAS { get; set; }
        public int? HazardClass { get; set; }
        public decimal? MaximumPermissibleConcentrationOneTimeMaximum { get; set; }
        public decimal? MaximumPermissibleConcentrationDailyAverage { get; set; }
        public decimal? ApproximateSafeExposureLevel { get; set; }
    }
}

Clever/Controllers/AirContaminantsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Clever.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Clever.Controllers
{
    public class AirContaminantsController : Controller
    {
        private readonly HttpApiClientController _HttpApiClient;

        public AirContaminantsController(HttpApiClientController HttpApiClient)
        {
            _HttpApiClient = HttpApiClient;
        }

        public async Task<IActionResult> Index(string SortOrder, string Name, string NumberCAS, int? HazardClass, int? PageSize, int? Page)
        {
            List<AirContaminant> airContaminants = new List<AirContaminant>();

            ViewBag.NameFilter = Name;
            ViewBag.NumberCASFilter = NumberCAS;
            ViewBag.HazardClassFilter = HazardClass;

            ViewBag.NameSort = SortOrder == "Name" ? "NameDesc" : "Name";
            ViewBag.NumberCASSort = SortOrder == "NumberCAS" ? "NumberCASDesc" : "NumberCAS";
            ViewBag.HazardClassSort = SortOrder == "HazardClass" ? "HazardClassDesc" : "HazardClass";

            string url = "api/AirContaminants",
                route = "",
                routeCount = "";
            if (!string.IsNullOrEmpty(SortOrder))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"SortOrder={SortOrder}";
            }
            if (!string.IsNullOrEmpty(Name))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Name={Name}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"Name={Name}";
            }
            if (!string.IsNullOrEmpty(NumberCAS))
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"NumberCAS={NumberCAS}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"NumberCAS={NumberCAS}";
            }
            if (HazardClass!=null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"HazardClass={HazardClass.ToString()}";
                routeCount += string.IsNullOrEmpty(routeCount) ? "?" : "&";
                routeCount += $"HazardClass={HazardClass.ToString()}";
            }
            if (PageSize != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"PageSize={PageSize.ToString()}";
                if (Page == null)
                {
                    Page = 1;
                }
            }
            if (Page != null)
            {
                route += string.IsNullOrEmpty(route) ? "?" : "&";
                route += $"Page={Page.ToString()}";
            }
            HttpResponseMessage response = await _HttpApiClient.GetAsync(url + route),
                responseCount = await _HttpApiClient.GetAsync(url + "/count" + routeCount);
            if (response.IsSuccessStatusCode)
            {
                airContaminants = await response.Content.ReadAsAsync<List<AirContaminant>>();
            }
            int airContaminantsCount = 0;
            if (responseCount.IsSuccessStatusCode)
            {
                airContaminantsCount = await responseCount.Content.ReadAsAsync<int>();
            }
            ViewBag.SortOrder = SortOrder;
            ViewBag.PageSize = PageSize;
            ViewBag.Page = Page != null ? (int)Page : 1;
            ViewBag.TotalPages = PageSize != null ? (int)(Math.Ceiling((decimal)airContaminantsCount / (decimal)PageSize)) : 1;
            ViewBag.StartPage = Page - 5;
            ViewBag.EndPage = Page + 4;
            if (ViewBag.StartPage <= 0)
            {
                ViewBag.EndPage -= (ViewBag.StartPage - 1);
                ViewBag.StartPage = 1;
            }
            if (ViewBag.EndPage > ViewBag.TotalPages)
            {
                ViewBag.EndPage = ViewBag.TotalPages;
                if (ViewBag.EndPage > 10)
                {
                    ViewBag.StartPage = ViewBag.EndPage - 9;
                }
            }
            IConfigurationSection pageSizeListSection = Startup.Configuration.GetSection("PageSizeList");
            var pageSizeList = pageSizeListSection.AsEnumerable();
            ViewBag.PageSizeList = new SelectList(pageSizeList.OrderBy(p => p.Key), "Value", "Value");

            return View(airContaminants);
        }

        public async Task<IActionResult> Details(int? id)
        {
            AirContaminant airContaminant = null;
            HttpResponseMessage response = await _HttpApiClient.GetAsync($"api/AirContaminants/{id.ToString()}");
            if (response.IsSuccessStatusCode)
            {
                airContaminant = await response.Content.ReadAsAsync<AirContaminant>();
            }
            return View(airContaminant);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name,NumberCAS,HazardClass,MaximumPermissibleConcentrationOneTimeMaximum,MaximumPermissibleConcentrationDailyAverage,ApproximateSafeExposureLevel")] AirContaminant airContaminant)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await _HttpApiClient.PostAsJsonAsync(
                    "api/AirContaminants", airContaminant);

                string OutputViewText = await response.Content.ReadAsStringAsync();
                OutputViewText = OutputViewText.Replace("<br>", Environment.NewLine);
                try
                {
                    response.EnsureSuccessStatusCode();
                }
                catch
                {
                    dynamic errors = JsonConvert.DeserializeObject<dynamic>(OutputViewText);
                    foreach (Newtonsoft.Json.Linq.JProperty property in errors.Children())
                    {
                        ModelState.AddModelError(property.Name, property.Value[0].ToString());
                    }
                    return View(airContaminant);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(airContaminant);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            AirContaminant airContaminant = null;
            HttpResponseMessage response = await _HttpApiClient.GetAsync($"api/AirContaminants/{id.ToString()}");
            if (response.IsSuccessStatusCode)
            {
                airContaminant = await response.Content.ReadAsAsync<AirContaminant>();
            }
            return View(airContaminant);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,NumberCAS,HazardClass,MaximumPermissibleConcentrationOneTimeMaximum,MaximumPermissibleConcentrationDailyAverage,ApproximateSafeExposureLevel")] AirContaminant airContaminant)
        {
            if (id != airContaminant.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await _HttpApiClient.PutAsJsonAsync(
                    $"api/AirContaminants/{airContaminant.Id}", airContaminant);

                string OutputViewText = await response.Content.ReadAsStringAsync();
                OutputViewText = OutputViewText.Replace("<br>", Environment.NewLine);
                try
                {
                    response.EnsureSuccessStatusCode();
                }
                catch
                {
                    dynamic errors = JsonConvert.DeserializeObject<dynamic>(OutputViewText);
                    foreach (Newtonsoft.Json.Linq.JProperty property in errors.Children())
                    {
                        ModelState.AddModelError(property.Name, property.Value[0].ToString());
                    }
                    return View(airContaminant);
                }

                airContaminant = await response.Content.ReadAsAsync<AirContaminant>();
                return RedirectToAction(nameof(Index));
            }
            return View(airContaminant);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AirContaminant airContaminant = null;
            HttpResponseMessage response = await _HttpApiClient.GetAsync($"api/AirContaminants/{id.ToString()}");
            if (response.IsSuccessStatusCode)
            {
                airContaminant = await response.Content.ReadAsAsync<AirContaminant>();
            }
            if (airContaminant == null)
            {
                return NotFound();
            }
            return View(airContaminant);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            HttpResponseMessage response = await _HttpApiClient.DeleteAsync(
                $"api/AirContaminants/{id}");
            return RedirectToAction(nameof(Index));
        }

        [DisableRequestSizeLimit]
        public IActionResult UploadFiles()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisableRequestSizeLimit]
        public async Task<string> UploadFiles(List<IFormFile> Files)
        {
            string report = "";
            foreach (IFormFile file in Files)
            {
                byte[] data;
                using (var br = new BinaryReader(file.OpenReadStream()))
                    data = br.ReadBytes((int)file.OpenReadStream().Length);

Clever/Views/AirContaminants/Create.cshtml
@model Clever.Models.AirContaminant

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>AirContaminant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberCAS" class="control-label"></label>
                <input asp-for="NumberCAS" class="form-control" />
                <span asp-validation-for="NumberCAS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HazardClass" class="control-label"></label>
                <input asp-for="HazardClass" class="form-control" />
                <span asp-validation-for="HazardClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationOneTimeMaximum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationDailyAverage" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationDailyAverage" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationDailyAverage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApproximateSafeExposureLevel" class="control-label"></label>
                <input asp-for="ApproximateSafeExposureLevel" class="form-control" />
                <span asp-validation-for="ApproximateSafeExposureLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clever/Views/AirContaminants/Delete.cshtml
@model Clever.Models.AirContaminant

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AirContaminant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberCAS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberCAS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HazardClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HazardClass)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApproximateSafeExposureLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApproximateSafeExposureLevel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Clever/Views/AirContaminants/Details.cshtml
@model Clever.Models.AirContaminant

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AirContaminant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberCAS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberCAS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HazardClass)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HazardClass)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationOneTimeMaximum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaximumPermissibleConcentrationDailyAverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApproximateSafeExposureLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApproximateSafeExposureLevel)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Clever/Views/AirContaminants/Edit.cshtml
@model Clever.Models.AirContaminant

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>AirContaminant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberCAS" class="control-label"></label>
                <input asp-for="NumberCAS" class="form-control" />
                <span asp-validation-for="NumberCAS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HazardClass" class="control-label"></label>
                <input asp-for="HazardClass" class="form-control" />
                <span asp-validation-for="HazardClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationOneTimeMaximum" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationOneTimeMaximum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaximumPermissibleConcentrationDailyAverage" class="control-label"></label>
                <input asp-for="MaximumPermissibleConcentrationDailyAverage" class="form-control" />
                <span asp-validation-for="MaximumPermissibleConcentrationDailyAverage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApproximateSafeExposureLevel" class="control-label"></label>
                <input asp-for="ApproximateSafeExposureLevel" class="form-control" />
                <span asp-validation-for="ApproximateSafeExposureLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clever/Views/AirContaminants/Index.cshtml
@model IEnumerable<Clever.Models.AirContaminant>
@using System.Net
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a> | <a asp-action="UploadFiles">Upload Files</a>
</p>
@using (Html.BeginForm("Index", "AirContaminants", new { SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter }, FormMethod.Get))
{
    @Html.Editor("SortOrder", null, new { htmlAttributes = new { @hidden = "hidden" }, value = ViewBag.SortOrder })
    @if (ViewBag.EndPage > 1)
    {
        <ul class="pagination">
            @if (ViewBag.Page > 1)
            {
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&laquo;&laquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&laquo;"), "Index",
                    new { PageSize = ViewBag.PageSize, Page = ViewBag.Page - 1, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }

            @for (var page = (int)ViewBag.StartPage; page <= (int)ViewBag.EndPage; page++)
            {
                <li class="@(page == ViewBag.Page ? "active" : "")">
                    @Html.ActionLink(page.ToString(), "Index",
                        new { PageSize = ViewBag.PageSize, Page = page, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }

            @if (ViewBag.Page < ViewBag.TotalPages)
            {
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&raquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, Page = ViewBag.Page + 1, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&raquo;&raquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, Page = ViewBag.TotalPages, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }
        </ul>
    }
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.ActionLink(Html.DisplayNameFor(c => c.ToList().FirstOrDefault().Name).ToString(), "Index",
                        new { PageSize = ViewBag.PageSize, SortOrder = ViewBag.NameSort, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                    <br />
                    @Html.Editor("Name", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                </th>
                <th>
                    @Html.ActionLink(Html.DisplayNameFor(c => c.ToList().FirstOrDefault().NumberCAS).ToString(), "Index",
                        new { PageSize = ViewBag.PageSize, SortOrder = ViewBag.NumberCASSort, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                    <br />
                    @Html.Editor("NumberCAS", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                </th>
                <th>
                    @Html.ActionLink(Html.DisplayNameFor(c => c.ToList().FirstOrDefault().HazardClass).ToString(), "Index",
                        new { PageSize = ViewBag.PageSize, SortOrder = ViewBag.HazardClassSort, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                    <br />
                    @Html.Editor("HazardClass", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
                </th>
                <th>
                    @Html.DropDownList("PageSize", (IEnumerable<SelectListItem>)ViewBag.PageSizeList, htmlAttributes: new { @class = "form-control" })
                    <input type="submit" value="Find" class="btn btn-default">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberCAS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HazardClass)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (ViewBag.EndPage > 1)
    {
        <ul class="pagination">
            @if (ViewBag.Page > 1)
            {
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&laquo;&laquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&laquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, Page = ViewBag.Page - 1, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }

            @for (var page = (int)ViewBag.StartPage; page <= (int)ViewBag.EndPage; page++)
            {
                <li class="@(page == ViewBag.Page ? "active" : "")">
                    @Html.ActionLink(page.ToString(), "Index",
                        new { PageSize = ViewBag.PageSize, Page = page, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }

            @if (ViewBag.Page < ViewBag.TotalPages)
            {
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&raquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, Page = ViewBag.Page + 1, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
                <li>
                    @Html.ActionLink(WebUtility.HtmlDecode("&raquo;&raquo;"), "Index",
                        new { PageSize = ViewBag.PageSize, Page = ViewBag.TotalPages, SortOrder = ViewBag.SortOrder, Name = ViewBag.NameFilter, NumberCAS = ViewBag.NumberCASFilter, HazardClass = ViewBag.HazardClassFilter })
                </li>
            }
        </ul>
    }
}

Clever/Views/AirContaminants/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UploadFiles</h2>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-form/jquery.form.js"></script>

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("UploadFiles", "AirContaminants", FormMethod.Post, new { enctype = "multipart/form-data", id = "uploadform" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="col-md-2 control-label">Files</label>
                <input type="file" name="Files" multiple />
            </div>
            <div class="form-group">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        }
    </div>
</div>

<div class="progress" style="width:50%">
    <div class="progress-bar"></div>
    <div class="percent">0%</div>
</div>

<div id="status"></div>

@if(!string.IsNullOrEmpty(ViewBag.Report))
{
    <div>
        @ViewBag.Report
    </div>
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        var bar = $('.progress-bar');
        var percent = $('.percent');
        var status = $('#status');
        $('#uploadform').ajaxForm({
            beforeSend: function () {
                status.empty();
                var percentVal = '0%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                bar.width(percentVal);
                percent.html(percentVal);
            },
            complete: function (xhr) {
                status.html(xhr.responseText);
            }
        });
    });
</script>